### ISSUE TITLE
Support LIS3DH

### ISSUE THREAD

**Issue by samuk** [rosmo-robot/smartcar_shield#3]
## Description
https://github.com/rosmo-robot/smartcar_shield/tree/master/src/sensors/heading
Add LIS3DH support to the lib

## Definition of Done

Sensor data from LIS3DH is available

**Comment by platisd** [comment]
[This one](https://github.com/adafruit/Adafruit_LIS3DH/blob/master/examples/acceldemo/acceldemo.ino) seems more tricky as the sensor's output is in `m/s^2` and not in degrees.
This means that some maths are needed and I am not personally interested in trying to figure that part out. Also, if I am not mistake this is only an accelerometer meaning that it is **not** good or suitable for determining the heading of a vehicle.

**Comment by samuk** [comment]
Hmm, thanks. We included this  ~$1 component without a great deal of research. It may be better to replace it with a ~$3 L3G4200D or MPU6050. I'll go and investigate a hardware change.

[Gyro vs accelerometer](https://learn.sparkfun.com/tutorials/gyroscope/all)

Looking at [Adafruit Gyro](https://github.com/search?q=org%3Aadafruit+gyroscope)

$3.60 [MPU6500](https://www.lcsc.com/product-detail/Attitude-Sensor-Gyroscope_TDK-InvenSense-TDK-InvenSense-MPU6500_C50278.html)

$3 [LSM6DSOTR ](https://www.lcsc.com/product-detail/Attitude-Sensor-Gyroscope_STMicroelectronics-LSM6DSOTR_C2655100.html)  (is this the same as LSM6DSOX?)
There is [code](https://github.com/arduino-libraries/Arduino_LSM6DSOX)  for the LSM6DSOX https://www.adafruit.com/product/4438
