### ISSUE TITLE
Evaluate MPU6500 as on-board IMU

### ISSUE THREAD

**Issue by samuk** [rosmo-robot/smartcar_shield#4]
## Description

Evaluate this as the 'onboard' budget IMU: https://www.lcsc.com/search?q=mpu6500

This lib looks most promising: https://github.com/wollewald/MPU9250_WE

This is the [MPU6500 example](https://github.com/wollewald/MPU9250_WE/blob/main/examples/MPU6500_all_data/MPU6500_all_data.ino) from that lib

## Definition of Done

Comments that the hardware/lib looks worth evaluating on real hardware.

**Comment by adityakamath** [comment]
I'll check it out. For starters, the 6500 seems to be related to the MPU6050 and MPU9250. I've used them before and there are multiple libraries to access data from them. Data from 6050 and 9250 is on the noisier side compared to BNO055 or similar IMUs, but decent enough given the price.

**Comment by samuk** [comment]
Great thanks, if people find the limitations of it they could always upgrade to the BNO085

**Comment by adityakamath** [comment]
Had a look at the sensor itself, looks good. From the documentation (of the library), MPU6500 seems to be a MPU9250 but without the magnetometer. I assume the library works (given the number of stars and watchers). If not, there are quite a lot of libraries around for the MPU9250/6500

IMO should be sufficient as an on-board IMU

**Comment by samuk** [comment]
Great, thanks. We'll add it to the board
